[package]
name = "whisky-uplc"
version = "1.0.3"
edition = "2021"
license = "Apache-2.0"
description = "Wrapper around the cardano-serialization-lib for easier transaction building, heavily inspired by cardano-cli APIs"
readme = "../../README.md"
authors = ["Wu Tsz Wai <tszwai@deltadefi.io>", "Hinson Wong <hinson.wong@deltadefi.io>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
uplc = "=1.1.16"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pallas-codec = { version = "0.32.0", features = ["num-bigint"] }
pallas-primitives = "0.32.0"
pallas-traverse = "0.32.0"
pallas-addresses = "0.32.0"
whisky-common = { version = "1.0.3", path = "../whisky-common" }
whisky-pallas = { version = "1.0.3", path = "../whisky-pallas" }
whisky-csl = { version = "1.0.3", path = "../whisky-csl" }