[package]
name = "whisky-examples"
version = "1.0.9"
edition = "2021"
license = "Apache-2.0"
description = "The Cardano Rust SDK, inspired by MeshJS"
readme = "../../README.md"
authors = ["Wu Tsz Wai <tszwai@deltadefi.io>", "Hinson Wong <hinson.wong@deltadefi.io>"]

[[bin]] # Bin to run the server
name = "whisky-examples"
path = "src/server.rs"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
serde = "1.0.209"
whisky = { version = "=1.0.9", path = "../whisky" }
