[package]
name = "whisky-js"
version = "1.0.10"
edition = "2021"
license = "Apache-2.0"
description = "Wrapper around the cardano-serialization-lib for easier transaction building, heavily inspired by cardano-cli APIs"
readme = "../../README.md"
authors = ["Wu Tsz Wai <tszwai@deltadefi.io>", "Hinson Wong <hinson.wong@deltadefi.io>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
whisky-csl = { version = "1.0.10", path = "../whisky-csl" }
whisky-common = { version = "1.0.10", path = "../whisky-common" }

# non-wasm
[target.'cfg(not(all(target_arch = "wasm32", not(target_os = "emscripten"))))'.dependencies]
uplc = "=1.1.10"
wasm-bindgen = { version = "=0.2.92", features = ["serde-serialize"] }
rand_os = "0.1"
noop_proc_macro = "0.3.0"
cquisitor-lib = { git = "https://github.com/cardananium/cquisitor-lib.git", rev = "866ea4b550685d87ea1bbd634c8622d29b39f0bc" }

# wasm
[target.'cfg(all(target_arch = "wasm32", not(target_os = "emscripten")))'.dependencies]
serde-wasm-bindgen = "0.4.5"
# uplc = { version = "=1.0.26-alpha", default-features = false, features = ["native-secp256k1"] }
uplc = "=1.1.10"
wasm-bindgen = { version = "=0.2.92", features = ["serde-serialize"] }
rand_os = { version = "0.1", features = ["wasm-bindgen"] }
js-sys = "=0.3.69"
wasm-bindgen-futures = "=0.4.40"
cquisitor-lib = { git = "https://github.com/cardananium/cquisitor-lib.git", rev = "866ea4b550685d87ea1bbd634c8622d29b39f0bc" }

[profile.release]
# Tell `rustc` to optimize for small code size.
codegen-units = 1
opt-level = "s"
incremental = true
lto = true
