[package]
name = "whisky-common"
version = "1.0.7"
edition = "2021"
license = "Apache-2.0"
description = "The Cardano Rust SDK, inspired by MeshJS"
readme = "../../README.md"
authors = ["Wu Tsz Wai <tszwai@deltadefi.io>", "Hinson Wong <hinson.wong@deltadefi.io>"]

[dependencies]
uplc = "=1.1.9"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "0.8.8"
async-trait = "0.1.79"