# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Test

on:
  release:
    types: [created]
  pull_request:
    branches:
      - master

jobs:
  build-test:
    name: Build and test (${{ matrix.os }})

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
      BLOCKFROST_PREPROD_PROJECT_ID: ${{ secrets.BLOCKFROST_PREPROD_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: swatinem/rust-cache@v2
      - name: Build whisky-common
        run: >
          cd packages/whisky-common &&
          cargo build
          --locked
          --verbose

      - uses: actions/checkout@v3
      - uses: swatinem/rust-cache@v2
      - name: Build whisky-csl
        run: >
          cd packages/whisky-csl &&
          cargo build
          --locked
          --verbose

      - uses: actions/checkout@v3
      - uses: swatinem/rust-cache@v2
      - name: Build whisky-js
        run: >
          cd packages/whisky-js &&
          cargo build
          --locked
          --verbose

      - uses: actions/checkout@v3
      - uses: swatinem/rust-cache@v2
      - name: Build whisky
        run: >
          cd packages/whisky &&
          cargo build
          --locked
          --verbose

      - name: Create .env file
        run: echo "MAESTRO_API_KEY=${MAESTRO_API_KEY}" > packages/whisky/.env

      - name: Run all tests (without coverage)
        if: matrix.os != 'ubuntu-latest'
        run: >
          cd packages &&
          cargo test
          --verbose
